# Sesi 4
Numpy

## Array

In [1]:
import numpy as np

In [2]:
# Creating Array, provide sendiri isinya
# List tidak ada tulisan 'array' di hasil cetakan

a = np.array([1,2,3])

a

array([1, 2, 3])

In [4]:
# Array dummies atau helper, isinya 0
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
# Array isi angka 1, yg di dalam kurung adl jumlah angka 1 yg dibutuhkan
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
# Array yg ambil angka dari array terakhir, array random
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
# Array isi elemen, 4 adalah jumlah elemen yg diprovide
np.arange(4)

array([0, 1, 2, 3])

In [9]:
# Array slicing
np.arange(3,20)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
# Array slicing (3 adalah mulai, 20 akhir tp tidak termasuk, 5 adl step atau loncatin 5-5)
np.arange(3,20,5)

array([ 3,  8, 13, 18])

In [11]:
# Add, Remove, and Sort

In [12]:
arrayAwal = np.array([1,2,3,4,5,6,7,8])

In [13]:
arrayAwal

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
print(arrayAwal)

[1 2 3 4 5 6 7 8]


In [16]:
# menambahkan isi ke array (append) arg1: nama var, arg2: list yg ingin ditambahkan
# JANGAN LUPA masukkan ke variabel baru

arrayBaru = np.append(arrayAwal, [1,2,3])

In [17]:
arrayBaru

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3])

In [19]:
# menghapus atau mengurangi elemen array, arg1: var, arg2: nomor posisi elemen yg mau dihapus
# JANGAN LUPA masukkan ke variabel baru

arrayBaru = np.delete(arrayBaru, 3)

In [20]:
arrayBaru

array([1, 2, 3, 5, 6, 7, 8, 1, 2, 3])

In [25]:
# deleting lebih dari 1
np.delete(arrayBaru, (1, 3))

array([1, 3, 6, 7, 8, 1, 2, 3])

In [24]:
# mengurutkan

np.sort(arrayBaru)

array([1, 1, 2, 2, 3, 3, 5, 6, 7, 8])

In [26]:
# Shape and Size
# untuk mengetahui bentuk dan ukuran array

In [27]:
arrayContoh = np.array ([[[0,1,2,3],
                         [4,5,6,7]],
                         [[0,1,2,3],
                         [4,5,6,7]],
                         [[0,1,2,3],
                         [4,5,6,7]]])

In [28]:
arrayContoh

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [30]:
# mengetahui dimensi

arrayContoh.ndim

3

In [31]:
# mengetahui ukuran, satu elemen atau angka dihitung 1

arrayContoh.size

24

In [32]:
# mengetahui bentuk array keseluruhan 
# (jumlah dimensi, jumlah baris/axis menurun, jumlah kolom/axis mendatar)
# SERING dipakai

arrayContoh.shape

(3, 2, 4)

In [33]:
# Reshape, bikin bentuk baru misal dari baris jadi kolom

In [34]:
a = np.arange(6)

a

array([0, 1, 2, 3, 4, 5])

In [35]:
b = a.reshape(3, 2)

In [36]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
b.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
b.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [39]:
# ERROR karena ada satu elemen sisa, gak bisa 6 dibagi jadi 4 baris, bawahnya ada yg kosong
b.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [40]:
# reshape ke dimensi lain (1D ke 2D)

a

array([0, 1, 2, 3, 4, 5])

In [42]:
b=a[np.newaxis]

In [43]:
b.shape

(1, 6)

In [44]:
a[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5]])

In [45]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [46]:
a

array([0, 1, 2, 3, 4, 5])

In [47]:
# jadi kolom
np.expand_dims(a, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [48]:
# jadi baris
np.expand_dims(a, axis=0)

array([[0, 1, 2, 3, 4, 5]])

In [49]:
# Indexing and Slicing

In [50]:
data = np.array([1,2,3])

In [51]:
print(data)

[1 2 3]


In [53]:
# Indexing

data[-1]

3

In [54]:
# Slicing
data[1:]

array([2, 3])

In [55]:
data[:]

array([1, 2, 3])

In [56]:
data[-2:]

array([2, 3])

In [57]:
a = np.array ([[1,2,3,4], 
               [5,6,7,8],
               [9,10,11,12]])

In [58]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
a[a<3]

array([1, 2])

In [60]:
a[(a>1) & (a<=6)]

array([2, 3, 4, 5, 6])

In [61]:
# Create array from existing data

In [63]:
arrayBaru

array([1, 2, 3, 5, 6, 7, 8, 1, 2, 3])

In [64]:
arrayBaru2 = arrayBaru[3:8]

In [65]:
arrayBaru2

array([5, 6, 7, 8, 1])

In [66]:
a_1 = np.array([[1,1], [2,2]])
a_2 = np.array([[3,3], [4,4]])

In [67]:
a_1

array([[1, 1],
       [2, 2]])

In [69]:
a_2

array([[3, 3],
       [4, 4]])

In [70]:
# tumpuk vertikal

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [71]:
# tumpuk horizontal

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [73]:
nArray=np.array([[1, 1, 3, 3,4,4,5,5,6,6,6,7,7,7,7],
              [2, 2, 4, 4,5,5,6,6,7,8,9,9,0,0,1]])
nArray

array([[1, 1, 3, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7, 7],
       [2, 2, 4, 4, 5, 5, 6, 6, 7, 8, 9, 9, 0, 0, 1]])

In [75]:
np.hsplit(nArray, 3)

[array([[1, 1, 3, 3, 4],
        [2, 2, 4, 4, 5]]),
 array([[4, 5, 5, 6, 6],
        [5, 6, 6, 7, 8]]),
 array([[6, 7, 7, 7, 7],
        [9, 9, 0, 0, 1]])]

In [81]:
np.vsplit(nArray, 2)

[array([[1, 1, 3, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7, 7]]),
 array([[2, 2, 4, 4, 5, 5, 6, 6, 7, 8, 9, 9, 0, 0, 1]])]

In [86]:
arrayBaru3=arrayBaru.view()

In [87]:
arrayBaru4=arrayBaru.copy()

In [88]:
arrayBaru3

array([1, 2, 3, 5, 6, 7, 8, 1, 2, 3])

In [89]:
arrayBaru4

array([1, 2, 3, 5, 6, 7, 8, 1, 2, 3])

In [90]:
# Basic Array Operations

In [91]:
data = np.array([1,2])
ones = np.ones(2)

In [92]:
data +ones

array([2., 3.])

In [93]:
data*ones

array([1., 2.])

In [94]:
data/data

array([1., 1.])

In [95]:
#menjumlah seluruh elemen dalam array
arrayBaru.sum()

38

In [96]:
a_1.sum()

6

In [97]:
#menjumlah menurun
a_1.sum(axis=0)

array([3, 3])

In [98]:
#menjumlah mendatar
a_1.sum(axis=1)

array([2, 4])

In [99]:
data * 1.6

array([1.6, 3.2])

In [100]:
arrayBaru *3

array([ 3,  6,  9, 15, 18, 21, 24,  3,  6,  9])

In [101]:
#cari value terkecil
arrayBaru.min()

1

In [102]:
#cari value terbesar
arrayBaru.max()

8

In [103]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
a.min()

1

In [106]:
a.max(axis=1)

array([ 4,  8, 12])

## Matrices

In [107]:
# Creating Matrices

In [108]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [109]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [110]:
np.random.random((3,2))

array([[0.97521051, 0.527071  ],
       [0.2102122 , 0.97510219],
       [0.24743353, 0.21991609]])

In [111]:
# Matrix Arithmetic

In [112]:
data = np.array([[1,2], [3,4]])

In [113]:
ones = np.ones([2,2])

In [114]:
data +ones

array([[2., 3.],
       [4., 5.]])

In [115]:
data * ones

array([[1., 2.],
       [3., 4.]])

In [116]:
# ERROR karena gabisa operasi sesuai posisi
data + arrayBaru

ValueError: operands could not be broadcast together with shapes (2,2) (10,) 

In [117]:
# Dot Product

In [118]:
a_1 = np.array(([[1,2,3], [4,5,6]]))
a_2 = np.array([[7,8], [9,10], [11,12]])

np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [119]:
# Matrix Indexing

In [120]:
data = np.array([[1,2], [3,4], [5,6]])

In [124]:
data[0,1]

2

In [125]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [126]:
data[0:2,1]

array([2, 4])

In [127]:
# Matrix Aggr

In [128]:
data.max()

6

In [129]:
# Transposing and Reshape

In [132]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [131]:
#rotating data
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [134]:
data.shape

(3, 2)

In [133]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
# N Dimensional Array

In [137]:
np.array([[[1,2], [3,4]],
         [[5,6], [7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [138]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [139]:
#flatten: jadiin matrix ke 1 dimensi array

In [140]:
arrflat=np.zeros((4,3))

In [141]:
arrflat.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])